### ISSUE TITLE
Keep All Header Values in Converted Attachment

### ISSUE THREAD

**Issue by nmmull** [uchicago-library/attachment-converter#39]
A small issue. We currently create a new header for converted attachments that only includes `Content-Type`, `Content-Disposition` and `Content-Transfer-Encoding`. I don't actually think I've ever seen any other headers, but no need to assume there aren't any. We can just take the header of the file we're converting and update it, carrying along all the other header values.

**Comment by bufordrat** [comment]
Yeah, definitely not a bad idea to copy over all the other headers as well.
