### ISSUE TITLE
Add meta-data header to attachments

### ISSUE THREAD

**Issue by nmmull** [uchicago-library/attachment-converter#42]
This is primarily in pursuit of idempotence of `acopy` and `amap`, but I thought I'd make a separate issue. We want to add a new header in the attachment of the form

```
X-Attachment-Converter: converted;
    source-type="application/pdf";
    target-type="application/pdf";
    original-file-name="name.pdf";
    timestamp="...";
    ...
```

**Comment by bufordrat** [comment]
Nice!  I like the header field parameters you're going with here.
